index:
   path: /
   controller: App\Controller\HomeController::index

film:
   path: /film
   controller: App\Controller\FilmController::index

serie:
   path: /serie
   controller: App\Controller\SerieController::index