import { Video } from './modeles/video';

export const SUGGESTION: Video[] = [
  {id_video: 1,
    titre: "ha",
    date_sortie: new Date(),
    poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
    plot: "histoir",
    trailer: "youtube.fr",
    vo: "FR"},
  {id_video: 2,
      titre: "juju",
      date_sortie: new Date(),
      poster: "https://m.media-amazon.com/images/M/MV5BNjk4MzVlM2UtZGM0ZC00M2M1LThkMWEtZjUyN2U2ZTc0NmM5XkEyXkFqcGdeQXVyOTAzMTc2MjA@._V1_SX300.jpg",
      plot: "histoir",
      trailer: "youtube.fr",
      vo: "FR"},
  {id_video: 3,
        titre: "haju",
        date_sortie: new Date(),
        poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
        plot: "histoir",
        trailer: "youtube.fr",
        vo: "FR"},
  {id_video: 4,
          titre: "string",
          date_sortie: new Date(),
          poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
          plot: "histoir",
          trailer: "youtube.fr",
          vo: "FR"},
          {id_video: 1,
            titre: "string",
            date_sortie: new Date(),
            poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
            plot: "histoir",
            trailer: "youtube.fr",
            vo: "FR"},
          {id_video: 2,
              titre: "string",
              date_sortie: new Date(),
              poster: "https://m.media-amazon.com/images/M/MV5BNjk4MzVlM2UtZGM0ZC00M2M1LThkMWEtZjUyN2U2ZTc0NmM5XkEyXkFqcGdeQXVyOTAzMTc2MjA@._V1_SX300.jpg",
              plot: "histoir",
              trailer: "youtube.fr",
              vo: "FR"},
          {id_video: 3,
                titre: "string",
                date_sortie: new Date(),
                poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                plot: "histoir",
                trailer: "youtube.fr",
                vo: "FR"},
          {id_video: 4,
                  titre: "string",
                  date_sortie: new Date(),
                  poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                  plot: "histoir",
                  trailer: "youtube.fr",
                  vo: "FR"},
                  {id_video: 1,
                    titre: "string",
                    date_sortie: new Date(),
                    poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                    plot: "histoir",
                    trailer: "youtube.fr",
                    vo: "FR"},
                  {id_video: 2,
                      titre: "string",
                      date_sortie: new Date(),
                      poster: "https://m.media-amazon.com/images/M/MV5BNjk4MzVlM2UtZGM0ZC00M2M1LThkMWEtZjUyN2U2ZTc0NmM5XkEyXkFqcGdeQXVyOTAzMTc2MjA@._V1_SX300.jpg",
                      plot: "histoir",
                      trailer: "youtube.fr",
                      vo: "FR"},
                  {id_video: 3,
                        titre: "string",
                        date_sortie: new Date(),
                        poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                        plot: "histoir",
                        trailer: "youtube.fr",
                        vo: "FR"},
                  {id_video: 4,
                          titre: "string",
                          date_sortie: new Date(),
                          poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                          plot: "histoir",
                          trailer: "youtube.fr",
                          vo: "FR"},
                          {id_video: 1,
                            titre: "string",
                            date_sortie: new Date(),
                            poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                            plot: "histoir",
                            trailer: "youtube.fr",
                            vo: "FR"},
                          {id_video: 2,
                              titre: "string",
                              date_sortie: new Date(),
                              poster: "https://m.media-amazon.com/images/M/MV5BNjk4MzVlM2UtZGM0ZC00M2M1LThkMWEtZjUyN2U2ZTc0NmM5XkEyXkFqcGdeQXVyOTAzMTc2MjA@._V1_SX300.jpg",
                              plot: "histoir",
                              trailer: "youtube.fr",
                              vo: "FR"},
                          {id_video: 3,
                                titre: "string",
                                date_sortie: new Date(),
                                poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                                plot: "histoir",
                                trailer: "youtube.fr",
                                vo: "FR"},
                          {id_video: 4,
                                  titre: "string",
                                  date_sortie: new Date(),
                                  poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                                  plot: "histoir",
                                  trailer: "youtube.fr",
                                  vo: "FR"},
                                  {id_video: 1,
                                    titre: "string",
                                    date_sortie: new Date(),
                                    poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                                    plot: "histoir",
                                    trailer: "youtube.fr",
                                    vo: "FR"},
                                  {id_video: 2,
                                      titre: "string",
                                      date_sortie: new Date(),
                                      poster: "https://m.media-amazon.com/images/M/MV5BNjk4MzVlM2UtZGM0ZC00M2M1LThkMWEtZjUyN2U2ZTc0NmM5XkEyXkFqcGdeQXVyOTAzMTc2MjA@._V1_SX300.jpg",
                                      plot: "histoir",
                                      trailer: "youtube.fr",
                                      vo: "FR"},
                                  {id_video: 3,
                                        titre: "string",
                                        date_sortie: new Date(),
                                        poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                                        plot: "histoir",
                                        trailer: "youtube.fr",
                                        vo: "FR"},
                                  {id_video: 4,
                                          titre: "string",
                                          date_sortie: new Date(),
                                          poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                                          plot: "histoir",
                                          trailer: "youtube.fr",
                                          vo: "FR"},
                                          {id_video: 1,
                                            titre: "string",
                                            date_sortie: new Date(),
                                            poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                                            plot: "histoir",
                                            trailer: "youtube.fr",
                                            vo: "FR"},
                                          {id_video: 2,
                                              titre: "string",
                                              date_sortie: new Date(),
                                              poster: "https://m.media-amazon.com/images/M/MV5BNjk4MzVlM2UtZGM0ZC00M2M1LThkMWEtZjUyN2U2ZTc0NmM5XkEyXkFqcGdeQXVyOTAzMTc2MjA@._V1_SX300.jpg",
                                              plot: "histoir",
                                              trailer: "youtube.fr",
                                              vo: "FR"},
                                          {id_video: 3,
                                                titre: "string",
                                                date_sortie: new Date(),
                                                poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                                                plot: "histoir",
                                                trailer: "youtube.fr",
                                                vo: "FR"},
                                          {id_video: 4,
                                                  titre: "string",
                                                  date_sortie: new Date(),
                                                  poster: "https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg",
                                                  plot: "histoir",
                                                  trailer: "youtube.fr",
                                                  vo: "FR"}
];

